export const ORDER_STATUS_PENDING = "PENDING";
export const ORDER_STATUS_CONFIRMED = "CONFIRMED";
export const ORDER_STATUS_SHIPPED = "SHIPPED";
export const ORDER_STATUS_DELIVERED = "DELIVERED";
